### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by dcorralf** [rrohitramsen/aws_jwt_cognito#2]
Hi Rohit Kumar,

I've interested in this code about Cognito, but I don't know if I can use it because there is not a license. I'm Computer Science Student and I will try to use it, can you add a license ? thanks !

**Comment by dcorralf** [comment]
Hi Rohit Kumar,

I've interested in this code about Cognito, but I don't know if I can use it because there is not a license. I'm Computer Science Student and I will try to use it, can you add a license ? a MIT license or Apache License for example. I would use your code for a univesity work, thanks a lot !!

**Comment by rrohitramsen** [comment]
Thanks David, I am adding it now

**Comment by dcorralf** [comment]
Ok great !! Thank you very much, It's a good work your code !!

Greetings.
